version: "3.3"
networks:
  grafananet:
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # extra_hosts: ['host.docker.internal: host-gateway']
    # user: "1761075855"
    # volumes:
    #   - ./config/grafana:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - grafananet

  Prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # extra_hosts: ['host.docker.internal: host-gateway']
    command: ["--config.file=/etc/prometheus/prometheus.yaml", "--enable-feature=native-histograms"]
    volumes:
      - /home/pankaj_kumar_ray/monitoringApplicationUsingGrafana/src/main/java/com/pankajdets/monitoringApplicationUsingGrafana/config/prometheus:/etc/prometheus
    ports:
      - '9090:9090'
    networks:
      - grafananet

  employee-management-application:
    build: ./
    container_name: employee-management-application
    ports:
      - 8080:8080
    networks:
      - grafananet


