version: "3.3"
networks:
  grafananet:
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    extra_hosts: ['host.docker.internal: host-gateway']
    user: "1761075855"
    volumes:
      - ./config/grafana:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - grafananet

  Prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    extra_hosts: ['host.docker.internal: host-gateway']
    command: ["--config.file=/etc/prometheus/prometheus.yaml", "--enable-feature=native-histograms"]
    volumes:
      - /Users/Pankaj.ray/.../config/prometheus:/etc/prometheus
    ports:
     - 9090:9090
    networks:
      - grafananet



