version: "3.3"
networks:
  grafananet:
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # extra_hosts: ['host.docker.internal: host-gateway']
    # user: "1761075855"
    volumes:
      - ./src/main/com/pankajdets/monitoringApplicationUsingGrafana/config/grafana:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - grafananet

  Prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # extra_hosts: ['host.docker.internal: host-gateway']
    command: ["--config.file=/etc/prometheus/prometheus.yaml", "--enable-feature=native-histograms"]
    volumes:
      - ./src/main/java/com/pankajdets/monitoringApplicationUsingGrafana/config/prometheus:/etc/prometheus
    ports:
      - '9090:9090'
    networks:
      - grafananet

  employee-management-application:
    build: ./
    container_name: employee-management-application
    ports:
      - 8080:8080
    networks:
      - grafananet

  loki:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./src/main/java/com/pankajdets/monitoringApplicationUsingGrafana/config/loki:/etc/loki
    ports:
      - "3100:3100"
    command: ["--config.file=/etc/loki/loki-config.yaml"]
    networks:
      - grafananet

  # tempo:
  #   image: grafana/tempo:1.5.0
  #   container_name: tempo
  #   command: ["--target=all", "--storage.trace.local.path=/var/tempo", "--multitenancy.enabled=false", "--search.enabled=true"]
  #   ports:
  #     - 4317:4317
  #   networks:
  #     - grafananet