global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus' #job to scrape prometheus metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.interval:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus' #job to scrape application metrics
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']
